insert into book values(1, 'test 1', 'test desc 1', 'test isbn 1');
insert into book values(2, 'test 2', 'test desc 2', 'test isbn 2');
insert into book values(3, 'test 3', 'test desc 3', 'test isbn 3');
insert into book values(4, 'test 4', 'test desc 4', 'test isbn 4');
insert into book values(5, 'test 5', 'test desc 5', 'test isbn 5');
insert into person values(1, 'Maciej', 'Butora', 'Żywiec');
insert into person values(2, 'Kacper', 'Butora', 'Żywiec');
insert into person values(3, 'Jan', 'Kowalski', 'Sosnowiec');
insert into person values(4, 'Janek', 'Kowalskowski', 'Silent Hill');
insert into person values(5, 'January', 'Kowalsky', 'Garby');
insert into person values(6, 'Jantete', 'Kowalskie', 'Sosnowiec');
insert into person values(7, 'Zuzanna', 'Butora', 'Żywiec');
insert into person values(8, 'Anna', 'Butora', 'Żywiec');